---
- name: Install Dependency packages
  package:
    name:
      - acl
      - sudo
      - python3-pexpect
      - lsb-release
      - wget
      - apt-transport-https
      - build-essential
      - python3-dev
      - libffi-dev
      - python3-pip
      - python3-setuptools
      - libpq5
      - libssl-dev
      - virtualenv
      - libjpeg-dev
      - libxslt1-dev
      - libxml2-dev
      - redis-server
      - nginx
    state: present

- name: Install Matrix Key
  ansible.builtin.apt_key:
    url: "{{ synapse_gpg_key }}"
    state: present

- name: Install Matrix Repository
  ansible.builtin.apt_repository:
    repo: "{{ synapse_repo }}"
    state: present
    update_cache: true
    validate_certs: true
    filename: "{{ synapse_name }}.list"
