---
- name: Install Synapse
  ansible.builtin.apt:
    name: matrix-synapse-py3
    state: present
    update_cache: true
    force: false
  register: apt_status
  until: apt_status is success
  delay: 6
  retries: 10
