---
- name: Edit synapse file already deployed
  ansible.builtin.replace:
    path: "{{ synapse_installed_config_file }}"
    regexp: "server_name: \"SERVERNAME\""
    replace: "server_name: \"{{ synapse_tld }}\""
    owner: "{{ synapse_service_user }}"
    group: "{{ synapse_service_user }}"
    mode: '0700'

# - name: Deploy fresh app config file
#   ansible.builtin.template:
#     src: "{{ synapse_deployed_config_file }}"
#     dest: "{{ synapse_dir }}/CONFIG_PATH"
#     force: true
#     mode: '0700'  # Ansible-Lint hates when this isn't set

# - name: Own all of the synapse folder
#   ansible.builtin.file:
#     path: "{{ synapse_dir }}"
#     state: directory
#     recurse: true
#     owner: '{{ synapse_service_user }}'
#     group: '{{ synapse_service_user }}'
