---
# - name: Template out synapse Service
#   ansible.builtin.template:
#     src: synapse.service.j2
#     dest: "/etc/systemd/system/synapse.service"
#     force: true
#     mode: '0644'  # Ansible-Lint hates when this isn't set

# - name: Add overwrite_certs.sh
#   ansible.builtin.template:
#     src: overwrite_certs.sh.j2
#     dest: "{{ synapse_dir }}/overwrite_certs.sh"
#     force: true
#     mode: '0700'  # Ansible-Lint hates when this isn't set
#     owner: "{{ synapse_service_user }}"
#     group: "{{ synapse_service_user }}"

# - name: Copy initial cert to appropriate directory
#   ansible.builtin.copy:
#     src: "{{ synapse_inital_cert_location }}/{{ synapse_external_domain }}.crt"
#     dest: "{{ synapse_certificate_path }}"
#     remote_src: true
#     force: true
#     owner: "{{ synapse_service_user }}"
#     group: "{{ synapse_service_user }}"
#     mode: "0700"

# - name: Copy initial key to appropriate directory
#   ansible.builtin.copy:
#     src: "{{ synapse_inital_cert_location }}/{{ synapse_external_domain }}.key"
#     dest: "{{ synapse_key_path }}"
#     remote_src: true
#     force: true
#     owner: "{{ synapse_service_user }}"
#     group: "{{ synapse_service_user }}"
#     mode: "0700"

# - name: Make override directory
#   ansible.builtin.file:
#     path: "{{ synapse_cert_renewer_path }}"
#     state: directory
#     mode: '0755'

# - name: Deploy synapse override
#   ansible.builtin.template:
#     src: cert-renewer.synapse.override.j2
#     dest: "{{ cert_renewer_path }}/override.conf"
#     force: true
#     mode: '0770'  # Ansible-Lint hates when this isn't set

# - name: Do post configuration activities for synapse
#   become_user: "{{ synapse_service_user }}"
#   ansible.builtin.command:
#     cmd: "{{ synapse_post_config_command }}"
#     chdir: "{{ synapse_dir }}"
#   changed_when: false

# - name: Ensure cert-renewer@bitwarden.timer is started
#   ansible.builtin.service:
#     name: "{{ synapse_cert_timer }}"
#     state: started
#     enabled: true

# - name: Ensure synapse is restarted
#   ansible.builtin.service:
#     name: "{{ synapse_name }}"
#     state: restarted
#     enabled: true
